server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  batch:
    job:
      enabled: false  # disable job execution when the application starts up.
    jdbc:
      platform: mysql
      initialize-schema: never
  datasource:
    url: jdbc:mysql://localhost:3306/batch_job?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# neo4j
  data:
    neo4j:
      repositories:
        type: reactive
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
    pool:
      max-connection-pool-size: 3

logging:
  level:
    root: info
    org.springframework.data.neo4j.core.transaction: debug
